# Generated by Django 5.0 on 2024-03-06 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educateur', '0009_feature_course_alter_course_features'),
        ('kids', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TakenCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educateur.course')),
                ('kid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kids.kids')),
            ],
        ),
    ]
