# Generated by Django 5.0 on 2024-03-16 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0002_takencourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idLessonVideo', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='takencourse',
            name='progress',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kids.courseprogress'),
        ),
    ]
