# Generated by Django 5.0 on 2024-01-30 10:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educateur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('title', models.CharField(max_length=150, unique=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(default=0, null=True)),
                ('is_approved', models.BooleanField(blank=True, default=True, null=True)),
                ('is_free', models.BooleanField(blank=True, default=True, null=True)),
                ('ratting', models.IntegerField(default=0, null=True)),
                ('level', models.CharField(choices=[('Facile', 'Facile'), ('Difficil', 'Difficil'), ('Intermediaire', 'Intermediaire')], max_length=25, null=True)),
                ('upload_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('categorie', models.CharField(max_length=150, unique=True)),
                ('educateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educateur.educateur')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educateur.course')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('content', models.TextField(blank=True, max_length=200, null=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educateur.chapter')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educateur.course')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.CharField(max_length=200, null=True)),
                ('url', models.CharField(max_length=200)),
                ('duration', models.FloatField(validators=[django.core.validators.MinValueValidator(0.3), django.core.validators.MaxValueValidator(60.0)])),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educateur.chapter')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educateur.course')),
            ],
        ),
    ]
