# Generated by Django 5.0 on 2024-02-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educateur', '0003_remove_course_slug_remove_lesson_slug_lesson_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
