# Generated by Django 5.0 on 2024-02-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educateur', '0004_video_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='categorie',
            field=models.CharField(max_length=150),
        ),
    ]
