# Generated by Django 5.0 on 2024-02-27 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educateur', '0006_feature_course_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(max_length=151, unique=True),
        ),
    ]
