# Generated by Django 5.0 on 2024-02-28 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educateur', '0008_course_update_time_alter_course_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='course_features', to='educateur.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='features',
            field=models.ManyToManyField(related_name='courses', to='educateur.feature'),
        ),
    ]
