# Generated by Django 5.0 on 2024-03-16 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educateur', '0009_feature_course_alter_course_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
