# Generated by Django 5.0 on 2024-03-16 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educateur', '0010_alter_chapter_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='type',
            field=models.CharField(default='lesson', max_length=6),
        ),
        migrations.AddField(
            model_name='video',
            name='type',
            field=models.CharField(default='video', max_length=5),
        ),
    ]
