# Generated by Django 5.0 on 2024-01-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_role_user_delete_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.PositiveSmallIntegerField(choices=[('kids', 'Kids'), ('admin', 'Admin'), ('psychologue', 'Psychologue'), ('educateur', 'Educateur')], primary_key=True, serialize=False),
        ),
    ]
