# Generated by Django 5.0 on 2024-01-02 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_role_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='roles',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
